class_name Enums

enum Phase { ACTION, PLAY, LIVE, SHOWDOWN }

enum ActionType {
	DRAW, PLAY_CARD, OPEN, ACTIVATE_SKILL, SKILL_EFFECT,
	TURN_START, TURN_END, ROUND_START, ROUND_END, PASS
}

enum DiffType {
	CARD_MOVE, CARD_FLIP, MODIFIER_ADD, MODIFIER_REMOVE,
	PROPERTY_CHANGE, INSTANCE_CREATE, INSTANCE_DESTROY
}

enum ModifierType { ICON_ADD, ICON_REMOVE, SUIT_ADD, SUIT_REMOVE }

enum ChoiceType { SELECT_CARD, SELECT_ZONE }

enum SkillType { PLAY, ACTION, PASSIVE }

enum SkillState { PENDING, RESOLVING, RESOLVED, COUNTERED }

enum TriggerEvent {
	SKILL_ACTIVATED, CARD_ENTERED_ZONE, CARD_LEFT_ZONE,
	CARD_FLIPPED, TURN_START, TURN_END
}

## ショウダウンのランク（値が小さいほど強い）
enum ShowdownRank { MIRACLE, TRIO, FLASH, DUO, CASUAL }
